# -*- coding: utf-8 -*-
"""Specification test protocol (§14) replayed on a real rig: a .blend
(Auto-Rig Pro by default) or a Rigify human generated on the fly.

Usage:
    blender <file.blend> --background --python tests/rig_protocol.py
    (Windows / Blender from the Store: powershell -File tests/run_rig_protocol.ps1 -Blend <file.blend>)
    PH_RIGIFY=1 blender --background --factory-startup --python tests/rig_protocol.py
    (PowerShell: powershell -File tests/run_rig_protocol.ps1 -Rigify)

Optional environment variables:
    PH_RIGIFY     1: generate Rigify's human meta-rig (bundled with Blender)
                  in an empty scene and replay the protocol on it
    PH_ARMATURE   armature name (default: the one deforming meshes)
    PH_BONE_L     left hand IK bone (default: c_hand_ik.l; hand_ik.L with PH_RIGIFY)
    PH_BONE_R     right hand IK bone (default: c_hand_ik.r; hand_ik.R with PH_RIGIFY)

The script creates a ball and a spear, replays both sections of the protocol
and numerically checks: no jump, no lag, no "Dependency cycle detected" in
Blender's output. Report: tests/rig_protocol.log. The .blend is not saved.
"""

import importlib
import os
import sys
import traceback

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
LOG_PATH = os.path.join(HERE, "rig_protocol.log")

_log_fd = os.open(LOG_PATH, os.O_WRONLY | os.O_CREAT | os.O_TRUNC)
os.dup2(_log_fd, 1)
os.dup2(_log_fd, 2)
sys.stdout = os.fdopen(1, "w", buffering=1, encoding="utf-8", errors="replace")
sys.stderr = sys.stdout

import bpy  # noqa: E402
from mathutils import Matrix, Vector  # noqa: E402

if ROOT not in sys.path:
    sys.path.insert(0, ROOT)
prop_handoff = importlib.import_module("prop_handoff")
utils = prop_handoff.utils

RESULTS = []
CYCLE_MARKER = "Dependency cycle detected"
RIGIFY = os.environ.get("PH_RIGIFY", "") not in ("", "0")
BONE_L = os.environ.get("PH_BONE_L", "hand_ik.L" if RIGIFY else "c_hand_ik.l")
BONE_R = os.environ.get("PH_BONE_R", "hand_ik.R" if RIGIFY else "c_hand_ik.r")


def check(label, condition, detail=""):
    status = "PASS" if condition else "FAIL"
    RESULTS.append((status, label))
    print("[%s] %s%s" % (status, label, (" -- " + str(detail)) if (detail and not condition) else ""))
    return bool(condition)


def mat_close(a, b, tol=1e-4):
    return all(abs(a[i][j] - b[i][j]) <= tol for i in range(4) for j in range(4))


def mat_str(m):
    return "T=%s" % (tuple(round(v, 4) for v in m.translation),)


def dg():
    return bpy.context.evaluated_depsgraph_get()


def world_of(obj):
    return utils.evaluated_matrix_world(dg(), obj)


def bone_world(arm, name):
    return utils.owner_world_matrix(dg(), arm.pose.bones[name])


def goto(frame):
    bpy.context.scene.frame_set(frame)


def cycle_count():
    sys.stdout.flush()
    try:
        os.fsync(1)
    except OSError:
        pass
    with open(LOG_PATH, encoding="utf-8", errors="replace") as handle:
        return handle.read().count(CYCLE_MARKER)


def run_op(operator, **kwargs):
    try:
        return operator(**kwargs)
    except RuntimeError as error:
        print("   operator error:", error)
        return {'CANCELLED'}


def generate_rigify():
    """Rigify human generated by the Rigify bundled with Blender, plus a mesh
    deformed by the rig (the add-on rejects a rig that deforms nothing)."""
    import addon_utils
    bpy.ops.wm.read_factory_settings(use_empty=True)
    addon_utils.enable("rigify", default_set=True, persistent=True)
    bpy.ops.object.armature_human_metarig_add()
    bpy.ops.pose.rigify_generate()
    rig = bpy.data.objects["rig"]
    mesh = bpy.data.meshes.new("PH_RigifyBody")
    mesh.from_pydata([(-0.2, -0.2, 0.0), (0.2, -0.2, 0.0), (0.2, 0.2, 0.0), (-0.2, 0.2, 0.0), (0.0, 0.0, 1.8)],
                     [], [(0, 1, 4), (1, 2, 4), (2, 3, 4), (3, 0, 4), (0, 3, 2, 1)])
    body = bpy.data.objects.new("PH_RigifyBody", mesh)
    bpy.context.scene.collection.objects.link(body)
    body.parent = rig
    body.modifiers.new("Armature", 'ARMATURE').object = rig
    print("Rigify:", rig.name, "|", len(rig.pose.bones), "bones | IK_Stretch =",
          rig.pose.bones["upper_arm_parent.L"].get("IK_Stretch"))
    return rig


def find_armature():
    name = os.environ.get("PH_ARMATURE")
    if name:
        return bpy.data.objects[name]
    scene = bpy.context.scene
    deforming = [ob for ob in scene.objects if ob.type == 'ARMATURE'
                 and utils.armature_deforms_something(ob, scene)]
    candidates = deforming or [ob for ob in scene.objects if ob.type == 'ARMATURE']
    candidates = [ob for ob in candidates if BONE_L in ob.pose.bones and BONE_R in ob.pose.bones]
    return candidates[0] if candidates else None


def make_box(name, size):
    mesh = bpy.data.meshes.new(name)
    sx, sy, sz = size
    verts = [(x, y, z) for x in (-sx, sx) for y in (-sy, sy) for z in (-sz, sz)]
    faces = [(0, 1, 3, 2), (4, 6, 7, 5), (0, 4, 5, 1), (2, 3, 7, 6), (0, 2, 6, 4), (1, 5, 7, 3)]
    mesh.from_pydata(verts, [], faces)
    mesh.update()
    obj = bpy.data.objects.new(name, mesh)
    bpy.context.scene.collection.objects.link(obj)
    return obj


def key_bone_location(pb, frame, delta):
    pb.keyframe_insert("location", frame=frame)
    pb.location = Vector(pb.location) + Vector(delta)
    pb.keyframe_insert("location", frame=frame)


def section1(arm, ball):
    print("\n== Section 1: ball + rig ==")
    scene = bpy.context.scene
    scene.prop_handoff.prop_object = ball
    settings = ball.prop_handoff
    goto(1)
    # The ball starts in the left hand.
    ball.matrix_world = Matrix.Translation(bone_world(arm, BONE_L).translation)
    bpy.context.view_layer.update()

    check("setup_prop", run_op(bpy.ops.prophandoff.setup_prop) == {'FINISHED'})
    for slot, bone in ((settings.slots[0], BONE_L), (settings.slots[1], BONE_R)):
        slot.target = arm
        slot.subtarget = bone
    check("slots -> %s / %s" % (BONE_L, BONE_R),
          [c.subtarget for c in utils.iter_ph_constraints(ball)] == [BONE_L, BONE_R])

    # Hand animation: the left one moves between 1 and 60.
    pb_l, pb_r = arm.pose.bones[BONE_L], arm.pose.bones[BONE_R]
    pb_l.keyframe_insert("location", frame=1)
    pb_l.location = Vector(pb_l.location) + Vector((0.15, 0.1, 0.2))
    pb_l.keyframe_insert("location", frame=60)
    pb_r.keyframe_insert("location", frame=1)
    pb_r.location = Vector(pb_r.location) + Vector((-0.1, 0.2, 0.1))
    pb_r.keyframe_insert("location", frame=60)

    goto(1)
    before = world_of(ball)
    check("frame 1: Assign Hand_L", run_op(bpy.ops.prophandoff.assign, slot_name="Hand_L") == {'FINISHED'})
    check("frame 1: the ball does not move", mat_close(before, world_of(ball)), "%s vs %s" % (mat_str(before), mat_str(world_of(ball))))
    check("header: Hand_L active", utils.active_slot_name(ball) == "Hand_L")
    goto(1)
    off1 = bone_world(arm, BONE_L).inverted() @ world_of(ball)
    goto(15)
    off15 = bone_world(arm, BONE_L).inverted() @ world_of(ball)
    check("the ball follows the bone (constant offset)", mat_close(off1, off15))

    history = {}
    for frame in range(1, 22):
        goto(frame)
        history[frame] = world_of(ball)
    goto(22)
    before = world_of(ball)
    check("frame 22: Assign Hand_R", run_op(bpy.ops.prophandoff.assign, slot_name="Hand_R") == {'FINISHED'})
    check("frame 22: no jump", mat_close(before, world_of(ball)))
    drift = [f for f in range(1, 22) if not (goto(f) or mat_close(history[f], world_of(ball)))]
    check("frames 1..21 unchanged", not drift, drift)

    goto(40)
    before = world_of(ball)
    check("frame 40: Throw", run_op(bpy.ops.prophandoff.throw, flight_frames=15) == {'FINISHED'})
    goto(40)
    check("frame 40: no jump at the release", mat_close(before, world_of(ball)))
    events = [(e["frame"], e["label"]) for e in utils.list_transfer_events(ball)]
    check("history [1 L, 22 R, 40 released]", events == [(1, "Left hand"), (22, "Right hand"), (40, "Released")], events)


def section2(arm, spear):
    print("\n== Section 2: spear + rig ==")
    scene = bpy.context.scene
    scene.prop_handoff.prop_object = spear
    settings = spear.prop_handoff
    settings.ik_object_l = arm
    settings.ik_bone_l = BONE_L
    settings.ik_object_r = arm
    settings.ik_bone_r = BONE_R
    check("valid IK targets", all(utils.ik_handle_error(spear, s) is None for s in utils.SIDES))
    check("the rig deforms meshes (not a duplicate)", utils.armature_deforms_something(arm, scene))

    # Frame 100: the hands are placed on the shaft (IK targets moved onto the spear).
    goto(100)
    pb_l, pb_r = arm.pose.bones[BONE_L], arm.pose.bones[BONE_R]
    mid = (bone_world(arm, BONE_L).translation + bone_world(arm, BONE_R).translation) * 0.5
    spear.matrix_world = Matrix.Translation(mid)
    bpy.context.view_layer.update()
    axis = (bone_world(arm, BONE_R).translation - bone_world(arm, BONE_L).translation)
    if axis.length < 1e-6:
        axis = Vector((1.0, 0.0, 0.0))
    axis.normalize()
    spear.rotation_euler = axis.to_track_quat('Y', 'Z').to_euler()
    bpy.context.view_layer.update()
    check("setup_twohanded (grips on the hands)", run_op(bpy.ops.prophandoff.setup_twohanded) == {'FINISHED'})
    for side, bone in (('LEFT', BONE_L), ('RIGHT', BONE_R)):
        grip = utils.find_grip_empty(spear, side)
        check("grip %s on the hand" % side, mat_close(world_of(grip), bone_world(arm, bone)))

    n0 = cycle_count()
    check("enable_grip_zone", run_op(bpy.ops.prophandoff.enable_grip_zone) == {'FINISHED'})
    goto(100)
    goto(101)
    check("console: no cycle after Enable", cycle_count() == n0)
    for side, bone in (('LEFT', BONE_L), ('RIGHT', BONE_R)):
        ev = arm.evaluated_get(dg()).pose.bones[bone]
        inf = ev.constraints[utils.gripblend_constraint_name(side)].influence
        check("influence %s = 1 on the grip" % side, abs(inf - 1.0) < 1e-4, inf)

    # Move the spear slightly: hands without lag.
    spear.keyframe_insert("location", frame=100)
    spear.keyframe_insert("rotation_euler", frame=100)
    spear.location = Vector(spear.location) + Vector((0.02, 0.01, 0.015))
    spear.keyframe_insert("location", frame=130)
    spear.keyframe_insert("rotation_euler", frame=130)
    lag = []
    for frame in (105, 115, 130):
        goto(frame)
        for side, bone in (('LEFT', BONE_L), ('RIGHT', BONE_R)):
            grip = utils.find_grip_empty(spear, side)
            if (bone_world(arm, bone).translation - world_of(grip).translation).length > 1e-4:
                lag.append((frame, side))
    check("hands on the grips at every frame (no lag)", not lag, lag)
    check("console: no cycle while following", cycle_count() == n0)

    # Move the right hand away: it lets go; back: it grabs again.
    goto(100)
    saved = Vector(pb_r.location)
    pb_r.location = saved + Vector((0.0, 0.0, 1.0))
    bpy.context.view_layer.update()
    inf = arm.evaluated_get(dg()).pose.bones[BONE_R].constraints["PH_GripBlend_R"].influence
    check("right hand moved away: influence 0", abs(inf) < 1e-4, inf)
    pb_r.location = saved
    bpy.context.view_layer.update()
    inf = arm.evaluated_get(dg()).pose.bones[BONE_R].constraints["PH_GripBlend_R"].influence
    check("right hand back: influence 1", abs(inf - 1.0) < 1e-4, inf)

    # Right master hand.
    goto(130)
    before_prop = world_of(spear)
    before_l = bone_world(arm, BONE_L)
    n1 = cycle_count()
    check("Master hand: Right", run_op(bpy.ops.prophandoff.set_master_hand, hand='RIGHT') == {'FINISHED'})
    goto(130)
    check("master hand: the spear does not jump", mat_close(before_prop, world_of(spear)), "%s vs %s" % (mat_str(before_prop), mat_str(world_of(spear))))
    check("master hand: the left hand does not jump", mat_close(before_l, bone_world(arm, BONE_L)))
    check("holding_side RIGHT", utils.holding_side(spear) == 'RIGHT')
    pb_r.keyframe_insert("location", frame=130)
    pb_r.location = Vector(pb_r.location) + Vector((0.02, -0.01, 0.02))
    pb_r.keyframe_insert("location", frame=160)
    goto(160)
    moved = (world_of(spear).translation - before_prop.translation).length
    check("the spear follows the right hand", 0.01 < moved < 0.06, moved)
    grip_l = utils.find_grip_empty(spear, 'LEFT')
    check("the left hand stays on it (Grip Zone)",
          (bone_world(arm, BONE_L).translation - world_of(grip_l).translation).length < 1e-3)
    check("console: no cycle in master hand", cycle_count() == n1)

    goto(160)
    before_prop = world_of(spear)
    check("Master hand: None", run_op(bpy.ops.prophandoff.set_master_hand, hand='NONE') == {'FINISHED'})
    goto(160)
    check("None: the spear does not jump", mat_close(before_prop, world_of(spear)))
    check("Release both hands", run_op(bpy.ops.prophandoff.release_both_hands) == {'FINISHED'})
    check("everything free", all(not utils.hand_follows_prop(spear, s) for s in utils.SIDES) and utils.holding_side(spear) is None)
    check("Grip Zone inactive", not any(utils.grip_zone_active(spear, s) for s in utils.SIDES))
    heads = {b: bone_world(arm, b).translation.copy() for b in (BONE_L, BONE_R)}
    spear.keyframe_insert("location", frame=160)
    spear.location = Vector(spear.location) + Vector((0.5, 0.5, 0.3))
    spear.keyframe_insert("location", frame=190)
    goto(190)
    check("no hand re-grabbed", all((heads[b] - bone_world(arm, b).translation).length < 1e-4 for b in heads))

    # Firm attach with the rig's own Child Of, c_traj moved (non-identity effect).
    goto(200)
    traj = arm.pose.bones.get("c_traj")
    if traj is not None:
        traj.keyframe_insert("location", frame=199)
        traj.location = Vector(traj.location) + Vector((0.3, 0.2, 0.0))
        traj.keyframe_insert("location", frame=200)
        bpy.context.view_layer.update()
    for side in utils.SIDES:
        run_op(bpy.ops.prophandoff.set_grip_pose, hand=side)
    before = {b: bone_world(arm, b) for b in (BONE_L, BONE_R)}
    n2 = cycle_count()
    check("Attach both hands", run_op(bpy.ops.prophandoff.attach_both_hands) == {'FINISHED'})
    goto(200)
    check("attach: no jump (rig Child Of active)", all(mat_close(before[b], bone_world(arm, b)) for b in before),
          {b: "%s vs %s" % (mat_str(before[b]), mat_str(bone_world(arm, b))) for b in before})
    spear.keyframe_insert("location", frame=200)
    spear.location = Vector(spear.location) + Vector((0.0, 0.0, 0.4))
    spear.keyframe_insert("location", frame=230)
    goto(200)
    offsets = {b: world_of(utils.find_grip_empty(spear, s)).inverted() @ bone_world(arm, b)
               for s, b in (('LEFT', BONE_L), ('RIGHT', BONE_R))}
    goto(230)
    check("attached hands: constant offsets", all(
        mat_close(world_of(utils.find_grip_empty(spear, s)).inverted() @ bone_world(arm, b), offsets[b])
        for s, b in (('LEFT', BONE_L), ('RIGHT', BONE_R))))
    before = {b: bone_world(arm, b) for b in (BONE_L, BONE_R)}
    check("Release", run_op(bpy.ops.prophandoff.release_both_hands) == {'FINISHED'})
    goto(230)
    check("release: no jump", all(mat_close(before[b], bone_world(arm, b)) for b in before))
    check("console: no cycle (attach)", cycle_count() == n2)

    # --- Lock + arm reach ---------------------------------------------------
    goto(250)
    # Folded arms (hands at 70 % of the reach), spear between the hands.
    operators = prop_handoff.operators
    for bone in (BONE_L, BONE_R):
        found = utils.find_ik_chain(arm, bone)
        if not check("IK chain found for %s" % bone, found is not None):
            continue
        chain, _shoulder = found
        root_head = bone_world(arm, chain[-1].name).translation
        head = bone_world(arm, bone).translation
        length = sum(b.bone.length for b in chain) * arm.matrix_world.to_scale().x
        target = root_head + (head - root_head).normalized() * (0.7 * length)
        matrix = bone_world(arm, bone).copy()
        matrix.translation = target
        operators.settle_owner(bpy.context, arm.pose.bones[bone], matrix, None, 250)
    goto(250)
    mid = (bone_world(arm, BONE_L).translation + bone_world(arm, BONE_R).translation) * 0.5
    spear.keyframe_insert("location", frame=249)
    spear.location = mid
    spear.keyframe_insert("location", frame=250)
    goto(250)
    for side in utils.SIDES:
        run_op(bpy.ops.prophandoff.set_grip_pose, hand=side)
    n3 = cycle_count()
    check("Lock", run_op(bpy.ops.prophandoff.grip_lock, action='LOCK') == {'FINISHED'})
    goto(250)
    goto(251)
    check("reach installed on both sides", utils.reach_sides(spear) == ['LEFT', 'RIGHT'], utils.reach_sides(spear))
    for side, bone in (('LEFT', BONE_L), ('RIGHT', BONE_R)):
        found = utils.find_ik_chain(arm, bone)
        if found is None or utils.ID_PROP_REACH[side] not in spear.keys():
            check("reach %s installed" % side, False)
            continue
        chain, shoulder = found
        reach = spear[utils.ID_PROP_REACH[side]]
        expected = sum(b.bone.length for b in chain) * arm.matrix_world.to_scale().x * (1.0 - settings.reach_margin)
        check("reach %s = %.3f (chain %s, shoulder %s)" % (side, expected, "→".join(b.name for b in chain), shoulder.name),
              abs(reach - expected) < 1e-5, reach)
    check("console: no cycle after Lock", cycle_count() == n3)
    # Push the spear one meter ahead: it stops, the hands stay on it.
    spear.keyframe_insert("location", frame=250)
    forward = (spear.matrix_world.to_3x3() @ Vector((0.0, 1.0, 0.0))).normalized()
    spear.location = Vector(spear.location) + forward * 1.0
    spear.keyframe_insert("location", frame=280)
    # Rule: the hand furthest beyond its reach (measured from the spear's
    # channels) is brought back exactly to its reach; a single translation
    # cannot guarantee both hands at once.
    over, lost, unclamped = [], [], []
    for frame in range(250, 281, 5):
        goto(frame)
        rotation = world_of(spear).to_3x3()
        overshoot = {}
        for side, bone in (('LEFT', BONE_L), ('RIGHT', BONE_R)):
            grip = utils.find_grip_empty(spear, side)
            helper = utils.find_helper(spear, utils.ID_PROP_REACH_HELPER[side])
            raw = (Vector(spear.location) + rotation @ grip.matrix_basis.translation
                   - world_of(helper).translation).length
            overshoot[side] = raw - spear[utils.ID_PROP_REACH[side]]
            if (bone_world(arm, bone).translation - world_of(grip).translation).length > 1e-3:
                lost.append((frame, side))
        worst = max(overshoot, key=overshoot.get)
        grip = utils.find_grip_empty(spear, worst)
        helper = utils.find_helper(spear, utils.ID_PROP_REACH_HELPER[worst])
        dist = (world_of(grip).translation - world_of(helper).translation).length
        if overshoot[worst] > 0.0 and abs(dist - spear[utils.ID_PROP_REACH[worst]]) > 1e-3:
            over.append((frame, worst, round(dist, 4), round(spear[utils.ID_PROP_REACH[worst]], 4)))
        if overshoot[worst] <= 0.0 and (world_of(spear).translation - Vector(spear.location)).length > 1e-4:
            unclamped.append((frame, "correction without overshoot"))
    check("the most extended hand is brought back to its reach at every frame", not over, over[:4])
    check("no correction while both hands are within reach", not unclamped, unclamped[:4])
    check("the hands stay on the spear (Lock)", not lost, lost[:4])
    goto(280)
    moved = (world_of(spear).translation - (Vector(spear.location) - forward * 1.0)).length
    check("the spear stopped (effective move %.2f < 1.0)" % moved, moved < 0.95, moved)
    check("console: no cycle (push)", cycle_count() == n3)

    # --- Continuity: push back and sideways (both hands out of reach in
    #     different directions — the old "most extended hand" rule jumped) --
    lateral = (spear.matrix_world.to_3x3() @ Vector((1.0, 0.0, 0.0))).normalized()
    goto(281)
    spear.location = mid
    spear.keyframe_insert("location", frame=281)
    spear.location = mid - forward * 0.8 + lateral * 0.8
    spear.keyframe_insert("location", frame=311)
    requested = (forward * 0.8 - lateral * 0.8).length / 30
    previous, previous_raw, jumps, out, lost = None, None, [], [], []
    for frame in range(282, 312):
        goto(frame)
        position = world_of(spear).translation.copy()
        raw = Vector(spear.location)
        # The projections are 1-Lipschitz: the stop never moves more than the
        # raw channels between two frames (the rig is still here).
        if previous is not None and (position - previous).length > (raw - previous_raw).length + 2e-3:
            jumps.append((frame, round((position - previous).length, 4), round((raw - previous_raw).length, 4)))
        previous, previous_raw = position, raw
        for side, bone in (('LEFT', BONE_L), ('RIGHT', BONE_R)):
            grip = utils.find_grip_empty(spear, side)
            helper = utils.find_helper(spear, utils.ID_PROP_REACH_HELPER[side])
            if (world_of(grip).translation - world_of(helper).translation).length > spear[utils.ID_PROP_REACH[side]] + 2e-3:
                out.append((frame, side))
            if (bone_world(arm, bone).translation - world_of(grip).translation).length > 1e-3:
                lost.append((frame, side))
    check("backward push: no jump (step <= raw step, average %.4f)" % requested, not jumps, jumps[:4])
    check("backward push: both grips within reach at every frame", not out, out[:4])
    check("backward push: hands stay on the spear", not lost, lost[:4])
    check("console: no cycle (backward push)", cycle_count() == n3)

    # --- Master hand under Lock: the stop moves to the master controller ----
    goto(315)
    spear.keyframe_insert("location", frame=314)
    spear.location = mid
    spear.keyframe_insert("location", frame=315)
    goto(315)
    before_prop = world_of(spear)
    check("Master hand: Left under Lock", run_op(bpy.ops.prophandoff.set_master_hand, hand='LEFT') == {'FINISHED'})
    goto(315)
    check("master: the spear does not jump", mat_close(before_prop, world_of(spear)))
    pb_l = arm.pose.bones[BONE_L]
    master = [c.name for c in utils.master_reach_constraints(pb_l)]
    check("master: reach constraints on the master controller (self + other)",
          "PH_ReachMaster_self" in master and "PH_ReachMaster_other" in master, master)
    helper_l = utils.find_helper(spear, utils.ID_PROP_REACH_HELPER['LEFT'])
    helper_r = utils.find_helper(spear, utils.ID_PROP_REACH_HELPER['RIGHT'])
    grip_l, grip_r = utils.find_grip_empty(spear, 'LEFT'), utils.find_grip_empty(spear, 'RIGHT')
    pb_l.keyframe_insert("location", frame=315)
    far = bone_world(arm, BONE_L).copy()
    far.translation = world_of(helper_l).translation + (far.translation - world_of(helper_l).translation).normalized() * 1.5
    utils.set_owner_world_matrix(pb_l, far, None)
    pb_l.keyframe_insert("location", frame=324)
    over_self, over_other, lost, jumps, previous = [], [], [], [], None
    for frame in range(315, 325):
        goto(frame)
        position = world_of(spear).translation.copy()
        if previous is not None and (position - previous).length > 0.25:
            jumps.append((frame, round((position - previous).length, 3)))
        previous = position
        if (bone_world(arm, BONE_L).translation - world_of(helper_l).translation).length > spear[utils.ID_PROP_REACH['LEFT']] + 2e-3:
            over_self.append(frame)
        if (world_of(grip_r).translation - world_of(helper_r).translation).length > spear[utils.ID_PROP_REACH['RIGHT']] + 2e-3:
            over_other.append(frame)
        for side, bone, grip in (('LEFT', BONE_L, grip_l), ('RIGHT', BONE_R, grip_r)):
            if (bone_world(arm, bone).translation - world_of(grip).translation).length > 1e-3:
                lost.append((frame, side))
    check("master: the master controller stays within its reach", not over_self, over_self)
    check("master: the other grip stays within the other arm's reach", not over_other, over_other)
    check("master: both hands stay on the spear", not lost, lost[:4])
    check("master: no jump while pushing", not jumps, jumps[:4])
    goto(324)
    moved = (world_of(spear).translation - before_prop.translation).length
    check("master: the spear stopped (moved %.2f < 1.5 requested)" % moved, moved < 1.0, moved)
    check("console: no cycle (master under Lock)", cycle_count() == n3)
    goto(325)
    before_prop = world_of(spear)
    check("Master hand: None (from Left under Lock)", run_op(bpy.ops.prophandoff.set_master_hand, hand='NONE') == {'FINISHED'})
    goto(325)
    check("None: the spear does not jump", mat_close(before_prop, world_of(spear)),
          "%s vs %s" % (mat_str(before_prop), mat_str(world_of(spear))))
    check("None: master reach constraints removed (baked)", not utils.master_reach_constraints(pb_l)
          and utils.find_helper(spear, utils.ID_PROP_REACH_TARGET['RIGHT']) is None)
    goto(320)
    check("None: history kept (controller still within reach at frame 320)",
          (bone_world(arm, BONE_L).translation - world_of(helper_l).translation).length <= spear[utils.ID_PROP_REACH['LEFT']] + 2e-3)
    check("console: no cycle (back to None)", cycle_count() == n3)

    goto(330)
    check("Unlock", run_op(bpy.ops.prophandoff.grip_lock, action='UNLOCK') == {'FINISHED'})
    goto(331)
    inf = spear.evaluated_get(dg()).constraints["PH_Reach"].influence
    check("reach inactive without Lock", abs(inf) < 1e-6, inf)
    check("reach removal", run_op(bpy.ops.prophandoff.reach_limit, action='DISABLE') == {'FINISHED'})
    run_op(bpy.ops.prophandoff.release_both_hands)
    run_op(bpy.ops.prophandoff.disable_grip_zone)
    check("console: no cycle (end of Lock)", cycle_count() == n3)


def main():
    print("Blender", bpy.app.version_string, "| file:", bpy.data.filepath or "(generated scene)")
    try:
        if RIGIFY:
            generate_rigify()
        prop_handoff.register()
        arm = find_armature()
        check("armature found", arm is not None, [o.name for o in bpy.data.objects if o.type == 'ARMATURE'])
        if arm is not None:
            print("armature:", arm.name, "| bones:", BONE_L, BONE_R,
                  "| parent of %s:" % BONE_L, arm.data.bones[BONE_L].parent.name if arm.data.bones[BONE_L].parent else None,
                  "| constraints:", [(c.name, c.type, round(c.influence, 2)) for c in arm.pose.bones[BONE_L].constraints])
            scene = bpy.context.scene
            scene.frame_start = 1
            scene.frame_end = max(scene.frame_end, 400)
            ball = make_box("PH_Test_Ball", (0.05, 0.05, 0.05))
            spear = make_box("PH_Test_Spear", (0.02, 0.6, 0.02))
            section1(arm, ball)
            section2(arm, spear)
        check("console: no cycle over the whole session", cycle_count() == 0)
        prop_handoff.unregister()
    except Exception:
        traceback.print_exc()
        RESULTS.append(("FAIL", "uncaught exception"))
    failed = [label for status, label in RESULTS if status == "FAIL"]
    print("\n==== %d tests, %d failure(s) ====" % (len(RESULTS), len(failed)))
    for label in failed:
        print("  FAIL:", label)
    print("RESULT:", "OK" if not failed else "FAILED")
    sys.stdout.flush()


main()
